from tkinter import *
window=Tk( )
window.title("Tkinter Sample Window")
window.geometry("300x300")
greetings=Label(text="Hello User",fg="black", bg="white")
button=Button(text="Click Me",fg="black", bg="white")
entry=Entry(fg="yellow", bg="white",width=50)
greetings.pack()
button.pack()
entry.pack()
frame=Frame(master=window,relief=RAISED,borderwidth=5)
label=Label(master=frame,text="Sample Frame")
frame.pack()
label.pack()
textbox=Text(fg="green",bg="yellow")
textbox.pack()